spring.datasource.url=jdbc:postgresql://localhost:5432/saas_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
google.client.id=410664552131-pu4ih4t7l2vj716rd78bgn18ju1og2u3.apps.googleusercontent.com
elevenlabs.api.key=sk_dcae78d57d8314b5eb29468fe1c8f9eaa8689060f63997af
elevenlabs.api.url=https://api.elevenlabs.io/v1/voices


